import type { Metadata } from "next";
import { Readex_Pro } from "next/font/google";
import "./globals.css";
import Header from "./components/shared/ui/Header";
import Footer from "./components/shared/ui/Footer";
import Newsletter from "./components/shared/ui/Newsletter";

const readexPro = Readex_Pro({
  variable: "--font-readex-pro",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "California",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${readexPro.variable} antialiased w-full **:border-box** p-0 m-0`}>
        <Header />
        <main className="min-h-screen w-full">{children}</main>
        <Newsletter />
        <Footer />
      </body>
    </html>
  );
}
